### ISSUE TITLE
Browscap project has closed

### ISSUE THREAD

**Issue by lecajer** [jonathaningram/JbiBrowscapBundle#1]
Causes this exception :

```
EXCEPTION : exception 'Exception' with message 'Bad datetime format from http://browsers.garykeith.com/versions/version-date.asp' in vendor/phpbrowscap/src/phpbrowscap/Browscap.php:504
```

See
https://github.com/GaretJax/phpbrowscap/issues/24

If we update URL's manually Capifony fell in error during deployment.

---

```
// In Broscap.php those properties are puclic :
public $remoteIniUrl = 'http://tempdownloads.browserscap.com/stream.php?BrowsCapINI';
public $remoteVerUrl = 'http://tempdownloads.browserscap.com/versions/version-date.php';
```

@jonathaningram  : Could we use a Factory to create the jbiBrowscap service that redifine those properties ?
http://symfony.com/doc/2.0/components/dependency_injection/factories.html

**Comment by jonathaningram** [comment]
You can probably use a service alias. http://symfony.com/doc/2.0/components/dependency_injection/advanced.html#aliasing

Or create a fork of the browscap project and update that with the correct URLs. Note: someone else may already have created a fork too.
